micronaut:
  application:
    name: casaDoCodigo
datasources:
  default:
    url: ${DB_URL:`jdbc:mysql://localhost:3306/cdc?createDatabaseIfNotExist=true`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:diasz}
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl.auto: update

cep:
  url: https://viacep.com.br/ws/
#jpa.default.properties.hibernate.hbm2ddl.auto: update

# POSTGRES
#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/cdc
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: root
#    dialect: POSTGRES



